name: Build Android APK (Capacitor)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install deps & build web
        run: |
          npm ci || npm install
          npm run build

      - name: Generate/sync Android project (Capacitor)
        run: |
          npx cap --version
          if [ ! -d android ]; then npx cap add android; fi
          npx cap sync android

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 34
          build-tools: 34.0.0
      - name: Accept SDK licenses
        run: yes | sdkmanager --licenses

      - name: Build APK (debug)
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Upload artifact (APK)
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
